Resources:
  snsPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Create a policy which will allow to send sms"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sns:publish
            Resource:
              - "*"
      ManagedPolicyName: ${self:custom.snsPolicyName}
