Resources:
  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: ${self:custom.userPoolClientName}
      GenerateSecret: false
      ExplicitAuthFlows:
        - CUSTOM_AUTH_FLOW_ONLY
      UserPoolId:
        Ref: CognitoUserPool
